## Lesson 8: Modules

from modules import function/class/object

bad practice: from module import *
only import things we need  

In [1]:
import sys
print(sys.path)

['/Users/xilezhang', '/Users/xilezhang/opt/anaconda3/lib/python38.zip', '/Users/xilezhang/opt/anaconda3/lib/python3.8', '/Users/xilezhang/opt/anaconda3/lib/python3.8/lib-dynload', '', '/Users/xilezhang/opt/anaconda3/lib/python3.8/site-packages', '/Users/xilezhang/opt/anaconda3/lib/python3.8/site-packages/aeosa', '/Users/xilezhang/opt/anaconda3/lib/python3.8/site-packages/locket-0.2.1-py3.8.egg', '/Users/xilezhang/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions', '/Users/xilezhang/.ipython']


### 1. Package

from package import module

#### 1.1 Sub-package

from package.subpackage import module

### 2. dir() function

dir(object): get all the methods and attributes defined in this object 

## Lesson 9: Python Standard Library

Files; SQLite; Date/Time; Random Values; Emails

### 1. Paths

In [13]:
from pathlib import Path

path = Path("/Users/xilezhang/Downloads/flu_shot.txt")
path.exists()   #这个文件是否存在
path.is_file()
print(path.name)
print(path.stem)
print(path.suffix)
print(path.parent)
#create a new path object based on this existing path but only change its name
path = path.with_name("file.txt")   
print(path.absolute())
#create a new path object based on this existing path but only change its suffix
path = path.with_suffix(".docx") 
print(path.absolute())

flu_shot.txt
flu_shot
.txt
/Users/xilezhang/Downloads
/Users/xilezhang/Downloads/file.txt
/Users/xilezhang/Downloads/file.docx


#### 1.2 Working with Files

In [21]:
from pathlib import Path
from time import ctime

path = Path("/Users/xilezhang/Downloads/flu_shot.txt")
#path.exists()
#path.raname("test.txt")
#path.unlink()  #delete the file
print(path.stat())  #返回这个文件的相关信息
#为了获取human readable time
print(ctime(path.stat().st_ctime))

#path.read_text()
#path.write_text("...")


os.stat_result(st_mode=33188, st_ino=8844208, st_dev=16777234, st_nlink=1, st_uid=501, st_gid=20, st_size=3519, st_atime=1639355712, st_mtime=1639355666, st_ctime=1639355710)
Sun Dec 12 19:35:10 2021


#### 1.3 Working with Zip Files

#### 1.4 Working with CVS Files

#### 1.5 Working with Json Files

#### 1.6 Working with a SQLite Database

### 2. Time

#### 2.1 Working with Timestamps

In [23]:
import time

print(time.time())  #返回当前时间，时间格式为时间戳，时间戳格式可用于时间计算

#计算该循环的运行时间
def send_emails():
    for i in range(10000):
        pass
    
start = time.time()
send_emails()
end = time.time()
duration = end - start
print(duration)  

1641167816.262479
0.0006883144378662109


#### 2.2 Working with DateTimes

In [32]:
import datetime

from datetime import datetime
dt = datetime(2018, 1, 1)  #create a datetime object

dt1 = datetime.now()
dt2 = datetime.strptime("2018/01/01", "%Y/%m/%d")  #convert string into datetime
dt = datetime.fromtimestamp(time.time())  #convert timestamp into datetime
print(dt)
print(f"{dt.year}/{dt.month}/{dt.day}")
print(dt.strftime("%Y/%m"))  #convert datetime into string

print(dt2 > dt1)

2022-01-02 19:07:37.041713
2022/1/2
2022/01
False


#### 2.3 Working with Time Deltas

In [36]:
from datetime import datetime, timedelta

dt1 = datetime(2018, 1, 1)
dt2 = datetime.now()

duration = dt2 - dt1
print(duration)
print("total_second:", duration.total_seconds())

dt3 = datetime(2018, 1, 1) + timedelta(days=1, seconds=1000)
print(dt3)

1462 days, 21:27:32.118367
total_second: 126394052.118367
2018-01-02 00:16:40


### 3. Generating Random Values

In [42]:
import random

print(random.random())  #产生[0，1]之间的随机值
print(random.randint(1, 10))
print(random.choice([1, 2, 3, 4, 5]))  #在列表值中随机抽样
print(random.choices([1, 2, 3, 4, 5], k=2))  #抽样数为2
#从字符串中随机抽样，抽样数为4，抽样结果以list格式呈现
print(random.choices("abcdefghij", k=4))  
#从字符串中随机抽样，抽样数为4，抽样结果以字符串格式呈现
print("".join(random.choices("abcdefghij", k=4)))  
print(",".join(random.choices("abcdefghij", k=4))) 

0.20309566404026658
9
3
[3, 1]
['c', 'j', 'h', 'a']
difg
f,g,j,e


In [49]:
import string

print(string.ascii_letters)
print(string.digits)
print(string.ascii_lowercase)

#生成四位验证码
print("".join(random.choices(string.ascii_letters + string.digits, k=4)))

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
abcdefghijklmnopqrstuvwxyz
5bAb


### 4. Opening the Browser

In [50]:
import webbrowser

webbrowser.open("https://www.bilibili.com/video/BV1ng4y1i7Uk?p=9")

True

### 5. Sending Emails

#### 5.1 Working with Templates

## Lesson 10: Python Package Index

https://pypi.org

## Lesson 11: Popular Python Packages

In [ ]:
Excel Spreadsheets/ PDFs/ Sending Text/ Browser Automation/ Web Scraping(爬虫)

### 1. Working with Excel Spreadsheets

In [53]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [54]:
pip install pylint

     |████████████████████████████████| 231 kB 9.9 MB/s eta 0:00:01
  Attempting uninstall: astroid
    Found existing installation: astroid 2.5
    Uninstalling astroid-2.5:
      Successfully uninstalled astroid-2.5
Note: you may need to restart the kernel to use updated packages.


In [61]:
import pandas as pd
import numpy as np
import os
from pandas import Series, DataFrame

df = pd.read_excel("/Users/xilezhang/OneDrive/transactions.xlsx")
print(df)



   transaction_id  product_id  price
0            1001           1   5.95
1            1002           2   6.95
2            1003           3   7.95


### 2. Numpy

array和矩阵(multi-dimensional array)操作，计算...

In [65]:
import numpy as np

array = np.array([1, 2, 3])   #create an array
array = np.array([ [1, 2, 3], [4, 5, 6] ])  #create a matrix
print(array)
print(array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [81]:
zero = np.zeros((3,4))  #默认format是float
print(zero)
zero = np.zeros((3,4), dtype=int)
print(zero)
one = np.ones((3,4), dtype=int)
print(one)
mt = np.full((3,4), 5, dtype=int)
print(mt)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [83]:
mt_rd = np.random.random((3,4))
print(mt_rd)
print(mt_rd[0,0])
print(mt_rd[mt_rd > 0.5])  #输出结果为一个array
print(np.sum(mt_rd))
print(np.floor(mt_rd))
print(np.ceil(mt_rd))

[[0.73923715 0.23978663 0.14264761 0.03618709]
 [0.80929279 0.90957609 0.86471273 0.03259816]
 [0.83844544 0.40428528 0.87385118 0.50363784]]
0.7392371511861635
[0.73923715 0.80929279 0.90957609 0.86471273 0.83844544 0.87385118
 0.50363784]
6.394257998488148
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [85]:
first = np.array([1, 2, 3])
second = np.array([3, 4, 5])
print(first + second)

dimensional_inch = np.array([1, 2, 3])
dimensional_cm = dimensional_inch * 2.54
print(dimensional_cm)

[4 6 8]
[2.54 5.08 7.62]


## Lesson 13: Machine Learning in Python

### 1. Machine Learning in Action

steps:
1. import the data
2. clean the data
3. split the data into training/test sets
4. create a model
5. train the model
6. make prediction
7. evaluate and improve

### 2. Libraries and Tools

Packages: Numpy Pandas(提供dataframe) MarPlotLib Scikit-Learn

### 3. Importing a Data Set

In [2]:
import pandas as pd

df = pd.read_csv("/Users/xilezhang/OneDrive/Python/Jupyter/vgsales.csv")  #return a dataframe
df.shape

(16598, 11)

In [4]:
df.describe()

Rank          Year      NA_Sales      EU_Sales      JP_Sales  \
count  16598.000000  16327.000000  16598.000000  16598.000000  16598.000000   
mean    8300.605254   2006.406443      0.264667      0.146652      0.077782   
std     4791.853933      5.828981      0.816683      0.505351      0.309291   
min        1.000000   1980.000000      0.000000      0.000000      0.000000   
25%     4151.250000   2003.000000      0.000000      0.000000      0.000000   
50%     8300.500000   2007.000000      0.080000      0.020000      0.000000   
75%    12449.750000   2010.000000      0.240000      0.110000      0.040000   
max    16600.000000   2020.000000     41.490000     29.020000     10.220000   

        Other_Sales  Global_Sales  
count  16598.000000  16598.000000  
mean       0.048063      0.537441  
std        0.188588      1.555028  
min        0.000000      0.010000  
25%        0.000000      0.060000  
50%        0.010000      0.170000  
75%        0.040000      0.470000  
max       10.570000     82.740000

In [5]:
df.values

array([[1, 'Wii Sports', 'Wii', ..., 3.77, 8.46, 82.74],
       [2, 'Super Mario Bros.', 'NES', ..., 6.81, 0.77, 40.24],
       [3, 'Mario Kart Wii', 'Wii', ..., 3.79, 3.31, 35.82],
       ...,
       [16598, 'SCORE International Baja 1000: The Official Game', 'PS2',
        ..., 0.0, 0.0, 0.01],
       [16599, 'Know How 2', 'DS', ..., 0.0, 0.0, 0.01],
       [16600, 'Spirits & Spells', 'GBA', ..., 0.0, 0.0, 0.01]],
      dtype=object)

### 4. Jupyter Shortcuts

In [ ]:
光标移到method，按shift+tab查看这个method的说明
command+/ : 备注或取消备注

### 5. A Real Problem

#### 5.1 import data

In [7]:
import pandas as pd
music_data = pd.read_csv("music.csv")
music_data

age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

#### 5.2 clean data

In [11]:
X = music_data.drop(columns=["genre"])   #产生一个新的drop掉genre列的dataframe，并不会改变music_data
y = music_data["genre"]

#### 5.3 learning and predicting

In [12]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X, y)
predictions = model.predict([ [21, 1], [22, 0] ])
predictions

array(['HipHop', 'Dance'], dtype=object)

#### 5.4 calculating the accuracy

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)  #randomly split

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

score = accuracy_score(y_test, predictions)
score

1.0

#### 5.5 persisting Models

once in a while we build and train a model and then we save it to a file 
next time when we want to make a prediction, we simply load the model from the file and ask it to make a prediction. we do not need to retrain it.

In [23]:
import joblib

joblib.dump(model, "music-recommender.joblib")
#文件夹里会出现music-recommender.joblib这个文件

['music-recommender.joblib']

In [25]:
model = joblib.load("music-recommender.joblib")
predictions = model.predict([[21, 1]])
predictions

array(['HipHop'], dtype=object)

#### 5.6 Visualizing Decision Trees

In [26]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

music_data = pd.read_csv("music.csv")
X = music_data.drop(columns=["genre"])   #产生一个新的drop掉genre列的dataframe，并不会改变music_data
y = music_data["genre"]

model = DecisionTreeClassifier()
model.fit(X, y)

#产生的dot文件在VSCode上可以打开
tree.export_graphviz(model, out_file="music-recommender.dot",
                    feature_names=["age", "gender"],
                    class_names=sorted(y.unique()),
                    label="all",
                    rounded=True,
                    filled=True)